### ISSUE TITLE
Improve the return type of get_jamo_class

### ISSUE THREAD

**Issue by JDongian** [JDongian/python-jamo#11]
Returning a string seems wrong, but returning a custom type seems worse. Find out what the *right way* to do this is.

**Comment by JDong820** [comment]
It's also not very multilingual... "tail"?

**Comment by JDong820** [comment]
https://stackoverflow.com/questions/36932/how-can-i-represent-an-enum-in-python found it. English is the standard for coding, so I will use English terms for enums.

**Comment by JDongian** [comment]
Strings feel right, actually.
