### ISSUE TITLE
updating distribution package to match with github version.

### ISSUE THREAD

**Issue by a3626a** [JDongian/python-jamo#33]
I think the package downloaded by 'pip install jamo' is older than commit 300415c30dab2f8d2622c8b8de03f433bf6d5960.
Because I got encoding error with it.
With git-cloned version, package is installed normally.

**Comment by JDongian** [comment]
Thanks for filing this issue! I will look into it.

**Comment by JDongian** [comment]
Issue should be fixed with version 0.4.1, uploaded to pypi. Thanks again.

**Comment by a3626a** [comment]
Installation is successfully done with new version.
Thank you.
