### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by mjfree92** [JDongian/python-jamo#34]
![screenshot from 2018-01-05 08-37-12](https://user-images.githubusercontent.com/22349748/34601411-d0ea9cba-f1f3-11e7-81f7-2626eccd056e.png)

As you guys writes kindly in ReadMe, I ran "sudo pip install python-jamo" but got the error in the picture.

It might be solvable without your effort, but could you check up what would be the reason for this?

In case it is about the version of Python that I'm using, please let me know.

Have a good day guys.

**Comment by JDongian** [comment]
Hi,

You need to use python 3, jamo does not support python 3.

Cheers and good luck,
Josh

**Comment by JDongian** [comment]
erm, sorry, I meant jamo only supports python 3 and does not support python
2
