### ISSUE TITLE
쌍- and cluster decomposition

### ISSUE THREAD

**Issue by brownbat** [JDongian/python-jamo#36]
I'd find it useful to be able to break down compound consonant and vowel clusters further, into their components.

ie, I might expect
`jamo.h2j('ㄸ') `
to produce
`ㄷㄷ`
rather than simply
`ㄸ`
as it does now. 

Also, having the inverse would be nice too:
`jamo.j2h('ㅅ','ㅅ','ㅏ','ㅇ')`
output:
`쌍`

Maybe a different step-up function would be required for that. I see this as very useful for Issue #7, though it might cause some ambiguities. As an example with random jamo, would `ㅇ ㅜ ㅅ ㅅ ㅡ ㅇ`  become `웃승` or `우씅`? Maybe you'd always just err on avoiding clusters unless required.

Same for ㄺ and ㅀ and the other 9(?) mixed consonant clusters. I think this gets wildly more complicated if you support old Hangul, which [seems to have](https://blogs.adobe.com/CCJKType/2012/12/old-hangul.html) occasional triple (or more?) letter clusters. Though don't quote me on that, I'm new to all this.

Even what I propose would break the model of assuming all characters are 2-3 jamo, so this might not be trivial.

An `.is_cluster()` or `.is_compound()` returning True or False as a supporting function might be useful too. Maybe having constants that have all the clusters, consonants, and vowels could be used so you could just say:
`jamo.is_consonant("ㄸ")`
`> True`
or 
`"ㄸ" in jamo.COMPOUNDS`
`> True`

I'm just starting to learn Korean and decided to write a short random grammar quiz for the vocab I know. One of the challenges was identifying final vowels in stems for conjugations, and identifying final consonants for irregulars. I started to write something to turn hangul to jamo before learning about the craziness of Hangul in Unicode. I was completely yak shaving until I found this great project.

Thanks for this, it's really useful!

**Comment by brownbat** [comment]
Oh you already have `_HCJ_VOWELS_MODERN`! Sorry, just digging through a little more carefully now...

**Comment by brownbat** [comment]
(Accidentally hit close)

**Comment by JDongian** [comment]
Hi, thanks for taking effort to make a PR. I know there are some hidden things I haven't documented yet -- they are just features I'm not ready to release and support yet.
* I agree with not changing existing behaviour.
* Ambiguity is bad, a `synthesize` function that changes the jamo makes no sense to me.
* I try to support all Hangul and jamo. There are some linguists who need to work with the old stuff.
* Interesting proposal. I had similar features in mind with all the global constants in jamo.py, but people who actually need to use it can simply use `if x in JAMO_LEADS` for now (or of course create a `set` first). These helper functions are on the roadmap, but I think there are better ways to implement than `in` (i.e. using unicode metadata).

**Comment by brownbat** [comment]
Glad I could help, thanks for all the tips, learned a lot. If I make progress on a refactor I'll send an update.
